### ISSUE TITLE
Create Templates

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/pythia-tutorials#2]
We plan to create a template tutorial in both `.md` and `.ipynb` format to help guide the tutorial creator on how to structure a tutorial. This template should be fairly loose as different speakers might have different styles (and that's okay!) 

but here is a good place to discuss things that SHOULD be included:

In the markdown (resembles the ESDS blog post):
- pre-requisites / target audience
- suggested videos from past tutorials to watch (is this part of a series, strictly dependent on any other tutorials?)
- installation steps (should be the same for all)
- a brief bio

In the notebook (the tutorial content):
- aim for 50 minutes
- reminder about target audience
- practice examples
- conclusion
- additional resources
- questions?

Anything else?

**Comment by clyne** [comment]
LGTM. Thanks!
